version: '3.1'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - desafio_data:/var/lib/postgresql/data
volumes:
  desafio_data: