version: '3.1'

services:

  api:
    image: edudu4/desafio_placeti:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/desafio
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./desafio:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=desafio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres